// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLog = "log"

// Log mapped from table <log>
type Log struct {
	ID       int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Imei     string  `gorm:"column:imei;not null" json:"imei"`
	Latitud  float64 `gorm:"column:latitud;not null" json:"latitud"`
	Longitud float64 `gorm:"column:longitud;not null" json:"longitud"`
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}
