// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameZonaVehiculo = "zona_vehiculos"

// ZonaVehiculo mapped from table <zona_vehiculos>
type ZonaVehiculo struct {
	ID            int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ZonaID        int32 `gorm:"column:zona_id;not null" json:"zona_id"`
	AvisarEntrada bool  `gorm:"column:avisar_entrada;not null" json:"avisar_entrada"`
	AvisarSalida  bool  `gorm:"column:avisar_salida;not null" json:"avisar_salida"`
}

// TableName ZonaVehiculo's table name
func (*ZonaVehiculo) TableName() string {
	return TableNameZonaVehiculo
}
