// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Log:          newLog(db, opts...),
		Zona:         newZona(db, opts...),
		ZonaVehiculo: newZonaVehiculo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Log          log
	Zona         zona
	ZonaVehiculo zonaVehiculo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Log:          q.Log.clone(db),
		Zona:         q.Zona.clone(db),
		ZonaVehiculo: q.ZonaVehiculo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Log:          q.Log.replaceDB(db),
		Zona:         q.Zona.replaceDB(db),
		ZonaVehiculo: q.ZonaVehiculo.replaceDB(db),
	}
}

type queryCtx struct {
	Log          *logDo
	Zona         *zonaDo
	ZonaVehiculo *zonaVehiculoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Log:          q.Log.WithContext(ctx),
		Zona:         q.Zona.WithContext(ctx),
		ZonaVehiculo: q.ZonaVehiculo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
